# Masukkan semua file c Anda
OBJS = ../../graphics/frame_buffer.c ../../graphics/draw.cpp drawByFile.cpp 

# frame_buffer.c draw.c object.cpp sample_object.cpp driver_sampleObject.cpp

CC = g++
# COMPILER_FLAGS = -o
LINKER_FLAGS = -std=c++11
OBJ_NAME = image
all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
